### ISSUE TITLE
Error trying to play music

### ISSUE THREAD

**Issue by tstern27** [tstern27/TimTheGateGuard#8]
Ran `https://www.youtube.com/watch?v=XlTDQ6V2IA8 0:39-0:46` and got the following
```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1265, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1332, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/jsinterp.py", line 150, in interpret_expression
    return obj[member]
TypeError: string indices must be integers
 (caused by TypeError('string indices must be integers'))
Ignoring exception in command play:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1265, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1332, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/jsinterp.py", line 150, in interpret_expression
    return obj[member]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1623, in _real_extract
    signature = self._decrypt_signature(sc['s'][0], video_id, player_url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1358, in _decrypt_signature
    raise ExtractorError(
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1265, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1332, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/jsinterp.py", line 150, in interpret_expression
    return obj[member]
TypeError: string indices must be integers
 (caused by TypeError('string indices must be integers'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/tim/wonderbot/cogs/youtube.py", line 137, in play
    player = await YTDLSource.from_url(url, ffmpeg_options, pre_op, loop=self.bot.loop)
  File "/home/tim/wonderbot/cogs/youtube.py", line 40, in from_url
    data = await loop.run_in_executor(None, lambda: ytdl.extract_info(url, download=not stream))
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tim/wonderbot/cogs/youtube.py", line 40, in <lambda>
    data = await loop.run_in_executor(None, lambda: ytdl.extract_info(url, download=not stream))
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1265, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1332, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/jsinterp.py", line 150, in interpret_expression
    return obj[member]
TypeError: string indices must be integers
 (caused by TypeError('string indices must be integers'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tim/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/tim/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/tim/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1265, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1332, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/jsinterp.py", line 150, in interpret_expression
    return obj[member]
TypeError: string indices must be integers
 (caused by TypeError('string indices must be integers'))
```

**Comment by tstern27** [comment]
youtube-dl was out of date
